# Site settings
title: 喷嚏图卦
email: dapenti@dapenti.com
description: 【喷嚏图卦】喷嚏网(www.dapenti.com)-阅读、发现和分享：8小时外的健康生活！
baseurl: ""
url: "http://www.pentitugua.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: posts/:title.html

# Build settings
markdown: kramdown
